adding:
  dependencies:
    config:
      - field.field.node.stanford_news.body
      - field.field.node.stanford_news.su_vpge_area_of_focus
      - field.field.node.stanford_news.su_vpge_related_fellowship
      - field.field.node.stanford_news.su_vpge_related_person
      - field.field.node.stanford_news.su_vpge_related_resource
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            1ccb4ee4-9a56-4ae4-ac92-1343889f1a94:
              uuid: 1ccb4ee4-9a56-4ae4-ac92-1343889f1a94
              region: main
              configuration:
                id: 'field_block:node:stanford_news:body'
                label: 'VPGE News body'
                label_display: '0'
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: text_default
                  label: hidden
                  settings: {  }
                  third_party_settings:
                    field_formatter_class:
                      class: ''
              weight: 1
              additional: {  }
  content:
    su_vpge_area_of_focus:
      type: entity_reference_label
      label: above
      settings:
        link: true
      third_party_settings: {  }
      weight: 12
      region: main
    su_vpge_related_fellowship:
      type: entity_reference_label
      label: above
      settings:
        link: true
      third_party_settings: {  }
      weight: 10
      region: main
    su_vpge_related_person:
      type: entity_reference_label
      label: above
      settings:
        link: true
      third_party_settings: {  }
      weight: 9
      region: main
    su_vpge_related_resource:
      type: entity_reference_label
      label: above
      settings:
        link: true
      third_party_settings: {  }
      weight: 11
      region: main
  hidden:
    body: true
removing: {  }
