adding:
  dependencies:
    config:
      - field.field.node.stanford_event.su_sul_event__image
      - field.field.node.stanford_event.su_vpge_area_of_focus
      - field.field.node.stanford_event.su_vpge_featured_event
      - field.field.node.stanford_event.su_vpge_fellowship_audience
      - field.field.node.stanford_event.su_vpge_fellowship_funding
      - field.field.node.stanford_event.su_vpge_grad_grow_competency
      - field.field.node.stanford_event.su_vpge_partner
      - field.field.node.stanford_event.su_vpge_person
      - field.field.node.stanford_event.su_vpge_program
      - field.field.node.stanford_event.su_vpge_resource
      - field.field.node.stanford_event.su_vpge_time_commitment
    module:
      - media_library
      - shs
  third_party_settings:
    field_group:
      group_editorial_content:
        weight: 3
      group_body_content:
        weight: 4
      group_event_details:
        weight: 5
      group_schedule_details:
        weight: 6
      group_vpge_categories:
        children:
          - su_vpge_featured_event
          - su_vpge_area_of_focus
          - su_vpge_fellowship_audience
          - su_vpge_fellowship_funding
          - su_vpge_grad_grow_competency
          - su_vpge_partner
          - su_vpge_person
          - su_vpge_program
          - su_vpge_resource
          - su_vpge_time_commitment
        label: 'VPGE Categories'
        region: content
        parent_name: ''
        weight: 0
        format_type: fieldset
        format_settings:
          classes: ''
          show_empty_fields: false
          id: ''
          description: ''
          required_fields: true
  content:
    status:
      weight: 7
    su_event_type:
      weight: 1
    su_sul_event__image:
      type: media_library_widget
      weight: 53
      region: content
      settings:
        media_types: {  }
      third_party_settings: {  }
    su_vpge_area_of_focus:
      type: options_buttons
      weight: 32
      region: content
      settings: {  }
      third_party_settings: {  }
    su_vpge_featured_event:
      type: boolean_checkbox
      weight: 31
      region: content
      settings:
        display_label: true
      third_party_settings: {  }
    su_vpge_fellowship_audience:
      type: options_buttons
      weight: 33
      region: content
      settings: {  }
      third_party_settings: {  }
    su_vpge_fellowship_funding:
      type: entity_reference_autocomplete
      weight: 34
      region: content
      settings:
        match_operator: CONTAINS
        match_limit: 10
        size: 60
        placeholder: ''
      third_party_settings: {  }
    su_vpge_grad_grow_competency:
      type: options_shs
      weight: 35
      region: content
      settings:
        display_node_count: false
        create_new_items: false
        create_new_levels: false
        force_deepest: false
      third_party_settings: {  }
    su_vpge_partner:
      type: entity_reference_autocomplete
      weight: 36
      region: content
      settings:
        match_operator: CONTAINS
        match_limit: 10
        size: 60
        placeholder: ''
      third_party_settings: {  }
    su_vpge_person:
      type: entity_reference_autocomplete
      weight: 37
      region: content
      settings:
        match_operator: CONTAINS
        match_limit: 10
        size: 60
        placeholder: ''
      third_party_settings: {  }
    su_vpge_program:
      type: entity_reference_autocomplete
      weight: 38
      region: content
      settings:
        match_operator: CONTAINS
        match_limit: 10
        size: 60
        placeholder: ''
      third_party_settings: {  }
    su_vpge_resource:
      type: entity_reference_autocomplete
      weight: 39
      region: content
      settings:
        match_operator: CONTAINS
        match_limit: 10
        size: 60
        placeholder: ''
      third_party_settings: {  }
    su_vpge_time_commitment:
      type: options_buttons
      weight: 40
      region: content
      settings: {  }
      third_party_settings: {  }
    title:
      weight: 2
    unpublish_on:
      type: datetime_timestamp_no_default
      weight: 13
      region: content
      settings: {  }
      third_party_settings: {  }
removing:
  third_party_settings:
    field_group:
      group_editorial_content:
        weight: 2
      group_body_content:
        weight: 3
      group_event_details:
        weight: 4
      group_schedule_details:
        weight: 5
  content:
    status:
      weight: 6
    su_event_type:
      weight: 0
    title:
      weight: 1
  hidden:
    unpublish_on: true
