adding:
  dependencies:
    config:
      - field.field.node.stanford_event.su_sul_event__image
      - field.field.node.stanford_event.su_vpge_area_of_focus
      - field.field.node.stanford_event.su_vpge_featured_event
      - field.field.node.stanford_event.su_vpge_fellowship_audience
      - field.field.node.stanford_event.su_vpge_fellowship_funding
      - field.field.node.stanford_event.su_vpge_grad_grow_competency
      - field.field.node.stanford_event.su_vpge_partner
      - field.field.node.stanford_event.su_vpge_person
      - field.field.node.stanford_event.su_vpge_program
      - field.field.node.stanford_event.su_vpge_resource
      - field.field.node.stanford_event.su_vpge_time_commitment
  third_party_settings:
    layout_builder_restrictions:
      allowed_block_categories:
        - Book
        - 'Changelog (Views)'
        - 'Policy (Views)'
        - Printable
        - 'Stanford SAML Authentication'
        - 'Taxonomy Terms (Views)'
        - User
        - 'VPGE views'
      entity_view_mode_restriction:
        restricted_categories:
          - Book
          - 'Changelog (Views)'
          - 'Policy (Views)'
          - Printable
          - 'Stanford SAML Authentication'
          - 'Taxonomy Terms (Views)'
          - User
          - 'VPGE views'
  content:
    su_sul_event__image:
      type: entity_reference_entity_view
      label: above
      settings:
        view_mode: default
        link: false
      third_party_settings: {  }
      weight: 121
      region: main
    su_vpge_area_of_focus:
      type: entity_reference_label
      label: above
      settings:
        link: true
      third_party_settings: {  }
      weight: 119
      region: main
    su_vpge_featured_event:
      type: boolean
      label: above
      settings:
        format: default
        format_custom_false: ''
        format_custom_true: ''
      third_party_settings: {  }
      weight: 120
      region: main
  hidden:
    su_vpge_fellowship_audience: true
    su_vpge_fellowship_funding: true
    su_vpge_grad_grow_competency: true
    su_vpge_partner: true
    su_vpge_person: true
    su_vpge_program: true
    su_vpge_resource: true
    su_vpge_time_commitment: true
removing:
  third_party_settings:
    layout_builder_restrictions:
      allowed_block_categories:
        - 'SimpleSAMLphp Authentication'
        - 'Stanford SimpleSAML PHP'
      entity_view_mode_restriction:
        restricted_categories:
          - 'SimpleSAMLphp Authentication'
          - 'Stanford SimpleSAML PHP'
