adding:
  dependencies:
    config:
      - field.field.node.stanford_person.su_vpge_area_of_focus
      - field.field.node.stanford_person.su_vpge_cohort
      - field.field.node.stanford_person.su_vpge_current_degree_dept
      - field.field.node.stanford_person.su_vpge_fellowship_funding
      - field.field.node.stanford_person.su_vpge_named_fellowship
      - field.field.node.stanford_person.su_vpge_program
  hidden:
    su_vpge_area_of_focus: true
    su_vpge_cohort: true
    su_vpge_current_degree_dept: true
    su_vpge_fellowship_funding: true
    su_vpge_named_fellowship: true
    su_vpge_pro: true
    su_vpge_program: true
removing:
  dependencies:
    config:
      - field.field.node.stanford_person.field_menulink
