adding:
  dependencies:
    config:
      - field.field.node.stanford_news.body
      - field.field.node.stanford_news.su_metatags
      - field.field.node.stanford_news.su_vpge_area_of_focus
      - field.field.node.stanford_news.su_vpge_related_fellowship
      - field.field.node.stanford_news.su_vpge_related_person
      - field.field.node.stanford_news.su_vpge_related_resource
  hidden:
    body: true
    su_vpge_area_of_focus: true
    su_vpge_related_fellowship: true
    su_vpge_related_person: true
    su_vpge_related_resource: true
removing: {  }
