adding:
  dependencies:
    config:
      - field.field.node.stanford_news.body
      - field.field.node.stanford_news.su_vpge_area_of_focus
      - field.field.node.stanford_news.su_vpge_related_fellowship
      - field.field.node.stanford_news.su_vpge_related_person
      - field.field.node.stanford_news.su_vpge_related_resource
    module:
      - text
  third_party_settings:
    field_group:
      group_categories_and_relationshi:
        children:
          - su_news_topics
          - su_vpge_area_of_focus
          - su_vpge_related_resource
          - su_vpge_related_fellowship
          - su_vpge_related_person
        label: 'Categories and Relationships'
        region: content
        parent_name: ''
        weight: 4
        format_type: fieldset
        format_settings:
          classes: ''
          show_empty_fields: false
          id: ''
          description: ''
          required_fields: false
  content:
    body:
      type: text_textarea_with_summary
      weight: 5
      region: content
      settings:
        rows: 9
        summary_rows: 3
        placeholder: ''
        show_summary: false
      third_party_settings: {  }
    publish_on:
      weight: 9
    scheduler_settings:
      weight: 8
    su_metatags:
      weight: 12
    su_news_components:
      weight: 3
    su_shared_tags:
      weight: 11
    su_vpge_area_of_focus:
      type: entity_reference_autocomplete
      weight: 4
      region: content
      settings:
        match_operator: CONTAINS
        match_limit: 10
        size: 60
        placeholder: ''
      third_party_settings: {  }
    su_vpge_related_fellowship:
      type: entity_reference_autocomplete
      weight: 6
      region: content
      settings:
        match_operator: CONTAINS
        match_limit: 10
        size: 60
        placeholder: ''
      third_party_settings: {  }
    su_vpge_related_person:
      type: entity_reference_autocomplete
      weight: 7
      region: content
      settings:
        match_operator: CONTAINS
        match_limit: 10
        size: 60
        placeholder: ''
      third_party_settings: {  }
    su_vpge_related_resource:
      type: entity_reference_autocomplete
      weight: 5
      region: content
      settings:
        match_operator: CONTAINS
        match_limit: 10
        size: 60
        placeholder: ''
      third_party_settings: {  }
    unpublish_on:
      type: datetime_timestamp_no_default
      weight: 10
      region: content
      settings: {  }
      third_party_settings: {  }
removing:
  content:
    publish_on:
      weight: 52
    scheduler_settings:
      weight: 50
    su_metatags:
      weight: 10
    su_news_components:
      weight: 4
    su_shared_tags:
      weight: 9
  hidden:
    unpublish_on: true
