adding:
  dependencies:
    config:
      - field.field.node.stanford_event.su_vpge_area_of_focus
      - field.field.node.stanford_event.su_vpge_featured_event
      - field.field.node.stanford_event.su_vpge_fellowship_audience
      - field.field.node.stanford_event.su_vpge_fellowship_funding
      - field.field.node.stanford_event.su_vpge_grad_grow_competency
      - field.field.node.stanford_event.su_vpge_partner
      - field.field.node.stanford_event.su_vpge_person
      - field.field.node.stanford_event.su_vpge_program
      - field.field.node.stanford_event.su_vpge_resource
      - field.field.node.stanford_event.su_vpge_time_commitment
  hidden:
    su_vpge_area_of_focus: true
    su_vpge_featured_event: true
    su_vpge_fellowship_audience: true
    su_vpge_fellowship_funding: true
    su_vpge_grad_grow_competency: true
    su_vpge_partner: true
    su_vpge_person: true
    su_vpge_program: true
    su_vpge_resource: true
    su_vpge_time_commitment: true
removing: {  }
