adding:
  permissions:
    - 'assign custm_vpge_site_manager role'
removing:
  dependencies:
    config:
      - node.type.stanford_policy
    module:
      - book
  permissions:
    - 'add content to books'
    - 'administer book outlines'
    - 'create new books'
    - 'create stanford_policy content'
    - 'delete any stanford_policy content'
    - 'delete own stanford_policy content'
    - 'delete stanford_policy revisions'
    - 'edit any stanford_policy content'
    - 'edit own stanford_policy content'
    - 'revert stanford_policy revisions'
    - 'view stanford_policy revisions'
