adding:
  third_party_settings:
    layout_builder_restrictions:
      allowed_block_categories:
        - 'Policy (Views)'
        - 'SimpleSAMLphp Authentication'
        - 'Stanford SimpleSAML PHP'
        - VPGE
        - 'VPGE '
        - 'VPGE views'
      entity_view_mode_restriction:
        allowlisted_blocks:
          Menus:
            - 'menu_block:fellowships-funding'
            - 'system_menu_block:fellowships-funding'
        restricted_categories:
          - 'Policy (Views)'
          - 'SimpleSAMLphp Authentication'
          - 'Stanford SimpleSAML PHP'
          - VPGE
          - 'VPGE '
removing: {  }
