<?php

/**
 * @file
 * Contains vpge_profile_helper.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function vpge_profile_helper_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the vpge_profile_helper module.
    case 'help.page.vpge_profile_helper':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('VPGE Profile Helper module') . '</p>';
      $output .= '<p>' . t('This module holds helper code specifically for the vpge_profile.') . '</p>';
      return $output;

    default:
  }
}

/**
 * implements hook_update_n
 */
function vpge_profile_helper_update_8201(&$sandbox) {
  $modules = ['fontawesome'];
  \Drupal::database()->delete('key_value')
    ->condition('collection', 'system.schema')
    ->condition('name', $modules, 'IN')
    ->execute();
}

/**
 * Implements hook_form_alter().
 */
function vpge_profile_helper_form_alter(&$form, &$form_state, $form_id) {
if ($it = $form_state->getValues('view')) {
  echo 'works';
}
  // Check if the form is the exposed filter form of your view.
/*  if ($form_id == 'views_exposed_form' && isset($form_state['view'])) {
    $view = $form_state['view'];

    // Check if it's the specific view you want to add the "Clear All" link to.
    if ($view->id() == 'vpge_grad_grow' && $view->current_display == "block_1") {
      // Add a "Clear All" button.
      $form['actions']['reset'] = array(
        '#type' => 'submit',
        '#value' => t('Clear All'),
        '#submit' => array('vpge_profile_helper_views_exposed_form_submit'),
      );
    }
  }*/
}

function vpge_profile_helper_views_exposed_form_submit($form, &$form_state) {
  // Reset all exposed filter values.
  $form_state['input'] = [];
}
